Cinemas/Cinemas/Cinemas/Controllers/LoginsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Cinemas.Models;
using Newtonsoft.Json;

namespace Cinemas.Controllers
{
    public class LoginsController : Controller
    {
        string Baseurl = @"http://localhost:8080/LuxeCinemas/api/";
        private LuxeCinemasEntities db = new LuxeCinemasEntities();

        // GET: Logins
        public ActionResult Index()
        {
            try
            {
                //var logins = db.Logins.Include(l => l.Customer);
                //return View(logins.ToList());
                return View();
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }


        // GET: Logins/Details/5
        public ActionResult Details()
        {
            try
            {
                var logins = db.Logins.Include(l => l.Customer);
                return View(logins.ToList());
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        // GET: Logins/Create
        //public ActionResult Create()
        //{
        //    try
        //    {
        //        ViewBag.CustomerId = new SelectList(db.Customers, "ID", "firstName");
        //        return View();
        //    }
        //    catch (Exception ex)
        //    {
        //        return View("~/Views/Shared/Error.cshtml");
        //    }
        //}


        // POST: Logins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,CustomerId,loginId,password,IsAdmin")] Login login)
        //{
        //    try
        //    {


        //        if (ModelState.IsValid)
        //        {
        //            db.Logins.Add(login);
        //            db.SaveChanges();
        //            return RedirectToAction("Index");
        //        }

        //        ViewBag.CustomerId = new SelectList(db.Customers, "ID", "firstName", login.CustomerId);
        //        return View(login);
        //    }
        //    catch (Exception ex)
        //    {
        //        return View("~/Views/Shared/Error.cshtml");
        //    }
        //}

        //GET: Logins/Create
        public async Task<ActionResult> Validate(Login login)
        {
            using (var client = new HttpClient())
            {
                try
                {
                    //Passing service base url  
                    client.BaseAddress = new Uri(Baseurl);

                    client.DefaultRequestHeaders.Clear();
                    //Define request data format  
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("text/plain"));

                    //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                    HttpResponseMessage Res = await client.GetAsync(string.Format("LoginDetails/login?loginId={0}&pwd={1}", login.loginId, login.password));

                    //Checking the response is successful or not which is sent using HttpClient  
                    if (Res.IsSuccessStatusCode)
                    {

                        var CustResponse = Res.Content.ReadAsStringAsync().Result;

                        //Deserializing the response recieved from web api and storing into the Employee list 
                        if (!string.Equals(JsonConvert.DeserializeObject<string>(CustResponse), "Invalid"))
                        {
                            Session["custId"] = JsonConvert.DeserializeObject<string>(CustResponse);
                            return RedirectToAction("Create", "Bookings");
                        }
                        else
                        {
                            return View("~/Views/Shared/LoginFailed.cshtml");
                        }

                    }
                    else
                    {
                        return View("~/Views/Shared/Error.cshtml");
                    }
                    
                    //returning the employee list to view  

                }
                catch (Exception ex)
                {
                    return View("~/Views/Shared/Error.cshtml");
                }
            }
        }

            


        //[HttpPost]
        //public ActionResult Validate(Login login)
        //{
        //    try
        //    {
        //        //var result = db1.Logins.Where(cls => cls.loginId.Equals(login.ID) && cls.password.Equals(login.password)).Any();
        //        string loginName = login.loginId;
        //        string pwd = login.password;
        //        var record = db.Logins.Where(u => u.loginId == loginName && u.password == pwd).FirstOrDefault();

        //        if (record != null && !string.IsNullOrEmpty(Convert.ToString(record.CustomerId)))
        //        {
        //            Session["CustId"] = Convert.ToString(record.CustomerId);
        //            return RedirectToAction("Create", "Bookings");

        //        }
        //        else
        //        {
        //            return View("~/Views/Shared/LoginFailed.cshtml");
        //        }
        //    }


        //    catch (Exception ex)
        //    {
        //        return View("~/Views/Shared/Error.cshtml");
        //    }


        //}


        // GET: Logins/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Login login = db.Logins.Find(id);
                if (login == null)
                {
                    return HttpNotFound();
                }
                ViewBag.CustomerId = new SelectList(db.Customers, "ID", "firstName", login.CustomerId);
                return View(login);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        // POST: Logins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CustomerId,loginId,password,IsAdmin")] Login login)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(login).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.CustomerId = new SelectList(db.Customers, "ID", "firstName", login.CustomerId);
                return View(login);
            }

            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        // GET: Logins/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Login login = db.Logins.Find(id);
                if (login == null)
                {
                    return HttpNotFound();
                }
                return View(login);
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        // POST: Logins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Login login = db.Logins.Find(id);
                db.Logins.Remove(login);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        protected override void Dispose(bool disposing)
        {

            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);


        }
    }
}

Cinemas/Cinemas/Cinemas/Views/Shared/LoginFailed.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login Failed!!</title>
</head>
<body>
    <hgroup>
        <h3>Login Failed - Invalid Credentials</h3>
        <h4>Invalid User Id or Password!! Please try again</h4>

    </hgroup>
    <a href="#">Forgot Password</a>
</body>
</html>

Cinemas/Cinemas/Cinemas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <link href="~/Content/Styles/style.css" rel="stylesheet" />
    <style type="text/css">
        a.my-class {
            color: white;
        }

            a.my-class:active {
                color: maroon;
            }

            a.my-class:link {
                color: white;
            }

            a.my-class:visited {
                color: white;
            }
    </style>
</head>

<body style="background-image: url('../../Content/Images/bg.jpg'); background-size: cover;">

    <center> <h2 style="align-content:center;color:white;font-size:xx-large; font-family:Constantia">LUXE Cinemas</h2></center>
    <div id="wowslider-container">
        <div class="ws_images">
            <ul>
                <li><a href="#"><img src="~/Content/Images/tombraider.jpg" alt="Tomb Raider" title="" id="wows_0" /></a></li>
                <li><a href="#"><img src="~/Content/Images/panther.jpg" alt="Black Panther" title="" id="wows_1" /></a></li>
                <li><a href="#"><img src="~/Content/Images/avengers.jpg" alt="Avengers" title="" id="wows_2" /></a></li>
                <li><a href="#"><img src="~/Content/Images/rabbit.jpg" alt="Rascal Rebel Rabbit" title="" id="wows_3" /></a></li>
                <li><a href="#"><img src="~/Content/Images/spidy.jpg" alt="Spider Man" title="" id="wows_4" /></a></li>
                <li><a href="#"><img src="~/Content/Images/wrinkle.jpg" alt="Wrinkle" title="" id="wows_5" /></a></li>
            </ul>
        </div>
        <div class="ws_bullets">
            <div>
                <a href="#" title=""><img src="~/Content/tooltips/tombraider.jpg" alt="Tomb Raider" />1</a>
                <a href="#" title=""><img src="~/Content/tooltips/panther.jpg" alt="Black Panther" />2</a>
                <a href="#" title=""><img src="~/Content/tooltips/avengers.jpg" alt="Avengers" />3</a>
                <a href="#" title=""><img src="~/Content/tooltips/rabbit.jpg" alt="Rascal Rebel Rabbit" />4</a>
                <a href="#" title=""><img src="~/Content/tooltips/spidy.jpg" alt="Spider Man" />5</a>
                <a href="#" title=""><img src="~/Content/tooltips/wrinkle.jpg" alt="Wrinkle" />6</a>
            </div>
        </div>
        <a href="#" class="ws_frame"></a>
        <div class="ws_shadow"></div>
    </div>
    <script type="text/javascript" src="~/Scripts/wowslider.js"></script>
    <script type="text/javascript" src="~/Scripts/script.js"></script>
    @*<div class="navbar-form">
            <img id="img_header" alt="Movies" src="@Url.Content("~/Content/Images/MoviesHeaderImage.png")" />
        </div>*@
    <div class="navbar-collapse collapse" style="padding-top:70px!important">
        <table class="table">
            <thead>
                <tr></tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2" width="10%">
                        <ul class="nav navbar-nav">
                            <li>
                                <h5 style="color:black">Customer</h5>
                                <ol>
                                    @Html.ActionLink("Login", "Index", "Logins", null, new { @class = "my-class" })
                                </ol>
                            </li>
                            <li id="adminList">
                                <h5 style="color:black">Admin</h5>
                                <ol>@Html.ActionLink("Manage Customers", "Index", "Customers", null, new { @class = "my-class" })</ol>
                                <ol>@Html.ActionLink("Card Information", "Index", "CreditCards", null, new { @class = "my-class" })</ol>
                                <ol>@Html.ActionLink("Bookings Information", "Index", "Bookings", null, new { @class = "my-class" })</ol>

                            </li>
                        </ul>
                    </td>
                    <td width="90%">
                        <div class="container body-content">
                            @RenderBody()
                            <hr />
                            <footer>
                                <p>&copy; Luxe Cinemas</p>
                            </footer>
                        </div>
                    </td>
                </tr>

            </tbody>
        </table>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>